//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM
    {
        public int EXAM_ID { get; set; }
        public Nullable<System.DateTime> EXAM_DATE { get; set; }
        public Nullable<int> EXAM_FK_USER { get; set; }
        public string EXAM_NAME { get; set; }
        public Nullable<int> EXAM_USER_SCORE { get; set; }
    
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
