//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public TBL_USER()
        {
            this.EXAMs = new HashSet<EXAM>();
        }
    
        public int U_ID { get; set; }
        public string U_NAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_IMAGE { get; set; }
    
        public virtual ICollection<EXAM> EXAMs { get; set; }
    }
}
